version: "3.8"
services:
  postgres_container:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_database_volume:/var/lib/postgresql/data
    networks:
      - principal_network
  pgadmin4_container:
    container_name: pgadmin4_container
    image: pgadmin-image
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./sql_files:/var/lib/pgadmin/storage/admin_admin.com
      - pgadmin_volume:/var
    ports:
      - "5050:80"
    depends_on:
      - postgres_container
    networks:
      - principal_network
volumes:
  postgres_database_volume:
  pgadmin_volume:

networks:
  principal_network:
    name: principal_network