version: '3'
services:
  firefox:
    container_name: firefox-node
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - VNC_PASSWORD=root
    extra_hosts:
      - "host:172.19.0.1"
    networks:
      - docker_postgres_default
  chrome:
    container_name: chrome-node
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - VNC_PASSWORD=root
    networks:
      - docker_postgres_default
    extra_hosts:
      - "host:172.19.0.1"
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    extra_hosts:
      - "host:172.19.0.1"
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - docker_postgres_default
networks:
  docker_postgres_default:
    external: true
    



